[package]
name = "aws_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
aws_utils = { version = "0.1.0", path = "aws_utils" }
tokio = { version = "1.42.0", features = ["full"] }
env_logger = "0.11.6"
log = "0.4"
