[package]
name = "aws_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.12"
aws-sdk-s3 = "1.67.0"
log = "0.4"
tokio = { version = "1.42.0", features = ["full"] }
walkdir = "2.5.0"

[dev-dependencies]
env_logger = "0.11.6"

